#SERVER
server:
  port: 3009

spring:
  application:
    name: 'amigos'
  data.mongodb:
    uri: mongodb://localhost:27017/friends


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
