#SERVER
server:
  port: 3009

spring:
  application:
    name: 'amigos'
  profiles: heroku
  data.mongodb:
    uri: mongodb://localhost:27017/friends

eureka:
  instance:
    hostname: https://friendsc3app.herokuapp.com/
    home-page-url: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  password: ${USER_PASSWORD:akeruec3}
  client:
    serviceUrl:
      defaultZone: https://eurekaserverc3.herokuapp.com/
      non-secure-port: 80
      secure-port: 443
