#SERVER
server:
  port: 3009

spring:
  application:
    name: 'amigos'

  data.mongodb:
    uri: mongodb+srv://mongodb:admin@cluster0.0nt6w.mongodb.net/c3?retryWrites=true&w=majority

eureka:
  instance:
    hostname: https://friendsc3app.herokuapp.com/
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eurekaserverc3.herokuapp.com/eureka/