#SERVER
server:
  port: 3009

spring:
  application:
    name: 'amigos'

  data.mongodb:
    uri: mongodb://localhost:27017/friends

eureka:
  instance:
    hostname: https://friendsc3app.herokuapp.com/
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eurekaserverc3.herokuapp.com/eureka/